Repository HaCSBCU/hacsbcu.github.io, pull requests merged in 2018-07, with the labels that each got.

#108 Update Committee
  _data/committee.yml
  images/team/Alex.jpg
  images/team/Andrei.jpg
  images/team/Michael.jpg
  images/team/Oliver.jpg
  images/team/Pandelis.jpg
  images/team/Pending.jpg
  images/team/Rob.jpg
  images/team/Temas.jpg
  images/team/Tilly.jpg
  images/team/Tim.jpg
  images/team2017/Bethany.jpg
  images/team2017/Chris.jpg
  images/team2017/Luke.jpg
  images/team2017/Ollie.jpg
  images/team2017/Pandelis.jpg
  images/team2017/Tom.jpg
  index.html
Labels: bug

#106 I added a Welcome Bot
  .github/config.yml
Labels: enhancement, idea

#111 Add security headers
  .htaccess
  index.html
  style/jquery.min.js
Labels: enhancement

#110 Update Nokogiri version
  Gemfile.lock
Labels: bug, major

#126 Edit CODEOWNERS for upcoming committee
  .github/CODEOWNERS
Labels: E:1 Site 2.0, enhancement

#125 Updated navbar to always float at top
  about-us.html
  assets/css/main.css
  assets/js/main.js
  bullhacks.html
  committee.html
  events.html
  index.html
  templates/elements.html
  templates/generic.html
  terms.html
Labels: E:1 Site 2.0, bug
